#### 3. View and analyse the dataset using Pandas. 
*a. Read data from csv file Federal Aviation Authority (FAA) Dataset
*b. View content of the data
*c. View the dataset shape
*d. Show all the columns present in the dataset
*e. Extract the following attributes from the dataset: 
*'ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT'1 'FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG'
*f. Show missing values count for each column. 
*g. Clean the dataset and replace the fatal flag NaN with “No”
*h. Verify if the missing values are replaced.
*i. Remove all the observations where aircraft names (ACFT_MAKE_NAME) are not available
*j. Find the aircraft types and their occurrences in the dataset
*k. Display the observations where fatal flag is “Yes”.
*l. Show the accidents with fatality.

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings 
warnings.filterwarnings('ignore')

In [4]:
#Read data from csv file Federal Aviation Authority (FAA) Dataset
data=pd.read_csv('faa_ai_prelim.csv',sep=',')

In [5]:
#b. View content of the data

display(data)

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,No,19-FEB-16,18-FEB-16,23:55:00Z,TAVERNIER,Florida,NaN,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,Incident,FAA Miami FSDO-19,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No,19-FEB-16,18-FEB-16,22:14:00Z,TRENTON,New Jersey,NaN,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",Incident,FAA Philadelphia FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,No,19-FEB-16,18-FEB-16,17:10:00Z,ASHEVILLE,North Carolina,NaN,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",Incident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,No,19-FEB-16,18-FEB-16,00:26:00Z,TALKEETNA,Alaska,NaN,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",Incident,FAA Anchorage FSDO-03,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,No,08-FEB-16,31-DEC-15,17:00:00Z,SAN ANTONIO,Texas,NaN,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",Accident,FAA San Antonio FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,NaN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,NaN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
 #View the dataset shape
data.shape

(83, 42)

In [7]:
#Show all the columns present in the dataset

data.columns

Index(['UPDATED', 'ENTRY_DATE', 'EVENT_LCL_DATE', 'EVENT_LCL_TIME',
       'LOC_CITY_NAME', 'LOC_STATE_NAME', 'LOC_CNTRY_NAME', 'RMK_TEXT',
       'EVENT_TYPE_DESC', 'FSDO_DESC', 'REGIST_NBR', 'FLT_NBR', 'ACFT_OPRTR',
       'ACFT_MAKE_NAME', 'ACFT_MODEL_NAME', 'ACFT_MISSING_FLAG',
       'ACFT_DMG_DESC', 'FLT_ACTIVITY', 'FLT_PHASE', 'FAR_PART', 'MAX_INJ_LVL',
       'FATAL_FLAG', 'FLT_CRW_INJ_NONE', 'FLT_CRW_INJ_MINOR',
       'FLT_CRW_INJ_SERIOUS', 'FLT_CRW_INJ_FATAL', 'FLT_CRW_INJ_UNK',
       'CBN_CRW_INJ_NONE', 'CBN_CRW_INJ_MINOR', 'CBN_CRW_INJ_SERIOUS',
       'CBN_CRW_INJ_FATAL', 'CBN_CRW_INJ_UNK', 'PAX_INJ_NONE', 'PAX_INJ_MINOR',
       'PAX_INJ_SERIOUS', 'PAX_INJ_FATAL', 'PAX_INJ_UNK', 'GRND_INJ_NONE',
       'GRND_INJ_MINOR', 'GRND_INJ_SERIOUS', 'GRND_INJ_FATAL', 'GRND_INJ_UNK'],
      dtype='object')

In [9]:
#Extract the following attributes from the dataset:
#'ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT'1 'FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG'
data[['ACFT_MAKE_NAME', 'LOC_STATE_NAME', 'ACFT_MODEL_NAME', 'RMK_TEXT', 'FLT_PHASE', 'EVENT_TYPE_DESC', 'FATAL_FLAG']]

,ACFT_MAKE_NAME,LOC_STATE_NAME,ACFT_MODEL_NAME,RMK_TEXT,FLT_PHASE,EVENT_TYPE_DESC,FATAL_FLAG
0,BEECH,North Carolina,36,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",UNKNOWN (UNK),Accident,Yes
1,VANS,Florida,RV7,AIRCRAFT ON LANDING WENT OFF THE END OF THE RU...,LANDING (LDG),Incident,NaN
2,CESSNA,New Jersey,172,"AIRCRAFT ON FINAL SUSTAINED A BIRD STRIKE, LAN...",APPROACH (APR),Incident,NaN
3,LANCAIR,North Carolina,235,"AIRCRAFT ON LANDING, GEAR COLLAPSED, ASHEVILLE...",LANDING (LDG),Incident,NaN
4,CESSNA,Alaska,172,"AIRCRAFT ON LANDING, NOSE GEAR COLLAPSED, TALK...",LANDING (LDG),Incident,NaN
...,...,...,...,...,...,...,...
78,AERONCA,Texas,O58B,"AIRCRAFT ON LANDING, GROUND LOOPED, BULVERDE A...",LANDING (LDG),Accident,NaN
79,NORTH AMERICAN,Arizona,F51,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",UNKNOWN (UNK),Accident,Yes
80,CHAMPION,California,8KCAB,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
81,BEECH,California,35,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",UNKNOWN (UNK),Accident,Yes
82,CESSNA,Alabama,182,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,UNKNOWN (UNK),Accident,Yes

In [10]:
#f
data.isnull().sum()

UPDATED                 0
ENTRY_DATE              0
EVENT_LCL_DATE          0
EVENT_LCL_TIME          0
LOC_CITY_NAME           0
LOC_STATE_NAME          0
LOC_CNTRY_NAME         81
RMK_TEXT                0
EVENT_TYPE_DESC         0
FSDO_DESC               2
REGIST_NBR              0
FLT_NBR                77
ACFT_OPRTR             76
ACFT_MAKE_NAME          5
ACFT_MODEL_NAME         4
ACFT_MISSING_FLAG      83
ACFT_DMG_DESC           1
FLT_ACTIVITY           70
FLT_PHASE               1
FAR_PART               82
MAX_INJ_LVL             3
FATAL_FLAG             75
FLT_CRW_INJ_NONE       19
FLT_CRW_INJ_MINOR      77
FLT_CRW_INJ_SERIOUS    82
FLT_CRW_INJ_FATAL      75
FLT_CRW_INJ_UNK        83
CBN_CRW_INJ_NONE       83
CBN_CRW_INJ_MINOR      83
CBN_CRW_INJ_SERIOUS    83
CBN_CRW_INJ_FATAL      83
CBN_CRW_INJ_UNK        82
PAX_INJ_NONE           66
PAX_INJ_MINOR          82
PAX_INJ_SERIOUS        80
PAX_INJ_FATAL          82
PAX_INJ_UNK            83
GRND_INJ_NONE          83
GRND_INJ_MINOR         83
GRND_INJ_SERIOUS       83
GRND_INJ_FATAL         83
GRND_INJ_UNK           82
dtype: int64

In [11]:
#g Clean the dataset and replace the fatal flag NaN with “No” 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83 entries, 0 to 82
Data columns (total 42 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   UPDATED              83 non-null     object
 1   ENTRY_DATE           83 non-null     object
 2   EVENT_LCL_DATE       83 non-null     object
 3   EVENT_LCL_TIME       83 non-null     object
 4   LOC_CITY_NAME        83 non-null     object
 5   LOC_STATE_NAME       83 non-null     object
 6   LOC_CNTRY_NAME       2 non-null      object
 7   RMK_TEXT             83 non-null     object
 8   EVENT_TYPE_DESC      83 non-null     object
 9   FSDO_DESC            81 non-null     object
 10  REGIST_NBR           83 non-null     object
 11  FLT_NBR              6 non-null      object
 12  ACFT_OPRTR           7 non-null      object
 13  ACFT_MAKE_NAME       78 non-null     object
 14  ACFT_MODEL_NAME      79 non-null     object
 15  ACFT_MISSING_FLAG    0 non-null      float64
 16  ACFT_DMG_DESC        82 non-null     object
 17  FLT_ACTIVITY         13 non-null     object
 18  FLT_PHASE            82 non-null     object
 19  FAR_PART             1 non-null      float64
 20  MAX_INJ_LVL          80 non-null     object
 21  FATAL_FLAG           8 non-null      object
 22  FLT_CRW_INJ_NONE     64 non-null     float64
 23  FLT_CRW_INJ_MINOR    6 non-null      float64
 24  FLT_CRW_INJ_SERIOUS  1 non-null      float64
 25  FLT_CRW_INJ_FATAL    8 non-null      float64
 26  FLT_CRW_INJ_UNK      0 non-null      float64
 27  CBN_CRW_INJ_NONE     0 non-null      float64
 28  CBN_CRW_INJ_MINOR    0 non-null      float64
 29  CBN_CRW_INJ_SERIOUS  0 non-null      float64
 30  CBN_CRW_INJ_FATAL    0 non-null      float64
 31  CBN_CRW_INJ_UNK      1 non-null      float64
 32  PAX_INJ_NONE         17 non-null     float64
 33  PAX_INJ_MINOR        1 non-null      float64
 34  PAX_INJ_SERIOUS      3 non-null      float64
 35  PAX_INJ_FATAL        1 non-null      float64
 36  PAX_INJ_UNK          0 non-null      float64
 37  GRND_INJ_NONE        0 non-null      float64
 38  GRND_INJ_MINOR       0 non-null      float64
 39  GRND_INJ_SERIOUS     0 non-null      float64
 40  GRND_INJ_FATAL       0 non-null      float64
 41  GRND_INJ_UNK         1 non-null      float64
dtypes: float64(22), object(20)
memory usage: 27.4+ KB

In [12]:

data['FATAL_FLAG'].replace(np.nan,"No")

0     Yes
1      No
2      No
3      No
4      No
     ...
78     No
79    Yes
80    Yes
81    Yes
82    Yes
Name: FATAL_FLAG, Length: 83, dtype: object

In [13]:
#i
data[data['ACFT_MAKE_NAME'].isnull().dropna()]

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
9,No,18-FEB-16,17-FEB-16,15:30:00Z,FERNANDINA BEACH,Florida,NaN,"AIRCRAFT, LSA PARADISE P1, ON LANDING NOSE GE...",Incident,FAA Orlando FSDO-15,...,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,No,17-FEB-16,15-FEB-16,16:12:00Z,PHOENIX,Arizona,NaN,"N2194X FIREFLY 9 BALLOON, ON LANDING STRUCK TH...",Incident,FAA Scottsdale FSDO-07,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,No,17-FEB-16,16-FEB-16,20:52:00Z,BUCKEYE,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
57,No,10-FEB-16,07-FEB-16,21:00:00Z,HELLS CANYON,Idaho,NaN,"AIRCRAFT ON LANDING GEAR COLLAPSED, HELLS CANY...",Incident,FAA Boise FSDO-11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,No,10-FEB-16,09-FEB-16,21:46:00Z,PALO ALTO,California,NaN,"AIRCRAFT, LIGHT SPORT DOVA AS SKYLARK, ON LAN...",Incident,FAA San Jose FSDO-15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
#j
data['ACFT_MAKE_NAME'].value_counts()

CESSNA                    23
PIPER                     10
BEECH                      9
MOONEY                     4
BOEING                     3
LANCAIR                    2
BELL                       2
CHAMPION                   2
SOCATA                     2
GRUMMAN                    1
AEROSTAR INTERNATIONAL     1
AIRBUS                     1
AERO COMMANDER             1
GULFSTREAM                 1
FLIGHT DESIGN              1
SABRELINER                 1
AERONCA                    1
PITTS                      1
EMBRAER                    1
ENSTROM                    1
MAULE                      1
VANS                       1
SAAB                       1
FAIRCHILD                  1
CONSOLIDATED VULTEE        1
GREAT LAKES                1
GLOBE                      1
HUGHES                     1
CHRISTEN                   1
NORTH AMERICAN             1
Name: ACFT_MAKE_NAME, dtype: int64

In [15]:
#k
data[data['FATAL_FLAG']=="Yes"]

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,No,17-FEB-16,16-FEB-16,20:52:00Z,BUCKEYE,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,No,12-FEB-16,11-FEB-16,11:32:00Z,DESTIN,Florida,United States,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,Accident,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
55,No,11-FEB-16,11-FEB-16,00:17:00Z,TULARE,California,NaN,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,Accident,FAA Fresno FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,NaN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,NaN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
#l
data[(data['EVENT_TYPE_DESC']=='Accident')&(data['FATAL_FLAG']=='Yes')]

,UPDATED,ENTRY_DATE,EVENT_LCL_DATE,EVENT_LCL_TIME,LOC_CITY_NAME,LOC_STATE_NAME,LOC_CNTRY_NAME,RMK_TEXT,EVENT_TYPE_DESC,FSDO_DESC,...,PAX_INJ_NONE,PAX_INJ_MINOR,PAX_INJ_SERIOUS,PAX_INJ_FATAL,PAX_INJ_UNK,GRND_INJ_NONE,GRND_INJ_MINOR,GRND_INJ_SERIOUS,GRND_INJ_FATAL,GRND_INJ_UNK
0,No,19-FEB-16,19-FEB-16,00:45:00Z,MARSHVILLE,North Carolina,NaN,"AIRCRAFT CRASHED INTO TREES, THE 1 PERSON ON B...",Accident,FAA Charlotte FSDO-68,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,No,17-FEB-16,16-FEB-16,20:52:00Z,BUCKEYE,Arizona,NaN,"AIRCRAFT, LIGHT SPORT EVOLUTION REVO, ON TAKE...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,No,12-FEB-16,11-FEB-16,11:32:00Z,DESTIN,Florida,United States,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES. ...,Accident,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
55,No,11-FEB-16,11-FEB-16,00:17:00Z,TULARE,California,NaN,AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES A...,Accident,FAA Fresno FSDO-17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,No,08-FEB-16,05-FEB-16,11:17:00Z,MARICOPA,Arizona,NaN,"AIRCRAFT CRASHED UNDER UNKNOWN CIRCUMSTANCES, ...",Accident,FAA Scottsdale FSDO-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,No,08-FEB-16,05-FEB-16,23:02:00Z,SAN PEDRO,California,NaN,"N9872R, BEECH M35 AIRCRAFT, AND N5057G, BELLAN...",Accident,FAA Long Beach FSDO-05,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Yes,02-FEB-16,02-FEB-16,01:52:00Z,MOBILE,Alabama,NaN,N784CP AIRCRAFT CRASHED INTO A WOODED AREA NEA...,Accident,FAA Birmingham FSDO-09,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN